'use client'

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ["latin"] });

/*export const metadata: Metadata = {
    title: "EVER",
    description: "Generated by create next app",
};*/

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const router = useRouter()

    const handleIndexClick = () => {
        router.push('/')
    }

    const handleLoginClick = () => {
        router.push('/login')
    }

    const handleRegisterClick = () => {
        router.push('/register')
    }

    return (
        <html lang="en">
        <body className={inter.className}>
            <div className="flex justify-between items-center top-0 left-0 w-screen m-0 py-0 bg-neutral-800">
                <div className="pl-10">
                    <button onClick={handleIndexClick} className="text-4xl font-bold text-blue-50 hover:text-blue-200
                    transition-all ease-in duration-300 delay-75">EVER</button>
                </div>
                <div className="h-full px-10">
                    <button onClick={handleLoginClick} className="text-16 text-blue-50 m-0 p-7 hover:text-blue-200
                    hover:bg-neutral-900 transition-all ease-in duration-300 delay-75">SIGN IN</button>
                    <button onClick={handleRegisterClick} className="text-16 text-blue-50 m-0 p-7 hover:text-blue-200
                    hover:bg-neutral-900 transition-all ease-in duration-300 delay-75">SIGN UP</button>
                </div>
            </div>
            {children}
        </body>
        </html>
    );
}
